import { CONTRACT_INTENT_CLASSIFICATION } from './intent.classification.js';
import { CONTRACT_LANGUAGE_DETECTION } from './language.detection.js';
import { CONTRACT_PERSONALITY_SELECTION } from './personality.selection.js';
import { CONTRACT_TOOL_ARGUMENT_EXTRACTION } from './tool.argument.extraction.js';
import { CONTRACT_TEXT_TRANSFORMATION } from './text.transformation.js';
import { CONTRACT_SCORING_EVALUATION } from './scoring.evaluation.js';
import { CONTRACT_STRICT_ANSWER } from './strict.answer.js';
import { CONTRACT_RESPONSE_FORMATTING } from './response.formatting.js';
import { CONTRACT_ERROR_CHANNEL } from './error.channel.js';

/**
 * Aggregated contracts.
 */
export const CONTRACTS = {
  INTENT_CLASSIFICATION: CONTRACT_INTENT_CLASSIFICATION,
  LANGUAGE_DETECTION: CONTRACT_LANGUAGE_DETECTION,
  PERSONALITY_SELECTION: CONTRACT_PERSONALITY_SELECTION,
  TOOL_ARGUMENT_EXTRACTION: CONTRACT_TOOL_ARGUMENT_EXTRACTION,
  TEXT_TRANSFORMATION: CONTRACT_TEXT_TRANSFORMATION,
  SCORING_EVALUATION: CONTRACT_SCORING_EVALUATION,
  STRICT_ANSWER: CONTRACT_STRICT_ANSWER,
  RESPONSE_FORMATTING: CONTRACT_RESPONSE_FORMATTING,
  ERROR_CHANNEL: CONTRACT_ERROR_CHANNEL,
} as const;
