import { CONTRACT_INTENT_CLASSIFICATION } from './intent.classification.js';
import { CONTRACT_LANGUAGE_DETECTION } from './language.detection.js';
import { CONTRACT_TOOL_ARGUMENT_EXTRACTION } from './tool.argument.extraction.js';
import { CONTRACT_TOOL_ARGUMENT_VERIFICATION } from './tool.argument.verification.js';
import { CONTRACT_TEXT_TRANSFORMATION } from './text.transformation.js';
import { CONTRACT_SCORING_EVALUATION } from './scoring.evaluation.js';
import { CONTRACT_STRICT_ANSWER } from './strict.answer.js';
import { CONTRACT_CONVERSATIONAL_ANSWER } from './conversational.answer.js';
import { CONTRACT_RESPONSE_FORMATTING } from './response.formatting.js';
import { CONTRACT_IMAGE_RECOGNITION } from './image.recognition.js';

/**
 * Aggregated contracts.
 */
export const CONTRACTS = {
  INTENT_CLASSIFICATION: CONTRACT_INTENT_CLASSIFICATION,
  LANGUAGE_DETECTION: CONTRACT_LANGUAGE_DETECTION,
  TOOL_ARGUMENT_EXTRACTION: CONTRACT_TOOL_ARGUMENT_EXTRACTION,
  TOOL_ARGUMENT_VERIFICATION: CONTRACT_TOOL_ARGUMENT_VERIFICATION,
  TEXT_TRANSFORMATION: CONTRACT_TEXT_TRANSFORMATION,
  SCORING_EVALUATION: CONTRACT_SCORING_EVALUATION,
  STRICT_ANSWER: CONTRACT_STRICT_ANSWER,
  CONVERSATIONAL_ANSWER: CONTRACT_CONVERSATIONAL_ANSWER,
  RESPONSE_FORMATTING: CONTRACT_RESPONSE_FORMATTING,
  IMAGE_RECOGNITION: CONTRACT_IMAGE_RECOGNITION,
} as const;
